INSERT INTO customers (name, shop, income) VALUES 
('Ivan Petrov', 'Sofia Market', 3200),
('Maria Georgieva', 'Varna Boutique', 4100),
('Georgi Dimitrov', 'Plovdiv Supermarket', 2900),
('Elena Kostova', 'Burgas Bakery', 3500),
('Nikolay Stoyanov', 'Ruse Electronics', 4700),
('Desislava Ivanova', 'Stara Zagora Pharmacy', 2800),
('Hristo Kolev', 'Veliko Tarnovo Antiques', 5300),
('Petya Marinova', 'Dobrich Toys', 2600),
('Vasil Popov', 'Shumen Clothing', 3900),
('Svetlana Borisova', 'Pleven Jewelry', 4500),
('Dimitar Angelov', 'Sliven Sports', 3400),
('Kristina Petrova', 'Pernik Home Goods', 3700),
('Todor Yordanov', 'Blagoevgrad Cafe', 3300),
('Margarita Staneva', 'Vidin Furniture', 4200),
('Stefan Vasilev', 'Kazanlak Garden Supplies', 3100),
('Borislava Mihailova', 'Lovech Auto Parts', 4800),
('Atanas Iliev', 'Montana Music Store', 2900),
('Silviya Zlateva', 'Kyustendil Florist', 3600),
('Emil Radev', 'Haskovo Bookstore', 4400),
('Ivanka Nikolaeva', 'Razgrad Pet Shop', 3000);